[package]
name = "rrgeo-cmd"
version = "0.1.0"
authors = ["Grant Miner <gx0r@protonmail.com>"]
edition = "2021"

[dependencies]
reverse_geocoder = { workspace = true }

[[bin]]
name = "rrgeo-cmd"
path = "src/cmdline.rs"
